services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false

databases:
  - name: n8n-db
    plan: starter-plus